### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by xyproto** [flosch/pongo2#139]
Hi,

When using pongo2 concurrently in [Algernon](https://github.com/xyproto/algernon), I get the following error:

```
fatal error: concurrent map read and map write

goroutine 66410 [running]:
runtime.throw(0xb50e1d, 0x21)
    /usr/lib/go/src/runtime/panic.go:566 +0x95 fp=0xc425745c60 sp=0xc425745c40
runtime.mapaccess2_faststr(0xa82b80, 0xc421090e10, 0xc420c55f18, 0x8, 0xc425c84240, 0xc425c84240)
    /usr/lib/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc425745cc0 sp=0xc425745c60
github.com/yuin/gopher-lua.(*LState).getFieldString(0xc4292c3700, 0x1066580, 0xc420f58a80, 0xc420c55f18, 0x8, 0xffffffffffffffff, 0x0)
    /home/afr/go/src/github.com/yuin/gopher-lua/state.go:916 +0x61b fp=0xc425745da8 sp=0xc425745cc0
github.com/yuin/gopher-lua.init.3.func7(0xc4292c3700, 0x18080000, 0xc429041000, 0x0)
    /home/afr/go/src/github.com/yuin/gopher-lua/vm.go:260 +0xb7 fp=0xc425745e10 sp=0xc425745da8
github.com/yuin/gopher-lua.mainLoop(0xc4292c3700, 0xc429041000)
    /home/afr/go/src/github.com/yuin/gopher-lua/vm.go:31 +0xd1 fp=0xc425745e40 sp=0xc425745e10
github.com/yuin/gopher-lua.(*LState).callR(0xc4292c3700, 0x2, 0xffffffffffffffff, 0x0)
    /home/afr/go/src/github.com/yuin/gopher-lua/state.go:873 +0x26e fp=0xc425745f30 sp=0xc425745e40
github.com/yuin/gopher-lua.(*LState).Call(0xc4292c3700, 0x2, 0xffffffffffffffff)
    /home/afr/go/src/github.com/yuin/gopher-lua/state.go:1601 +0x48 fp=0xc425745f60 sp=0xc425745f30
github.com/yuin/gopher-lua.(*LState).PCall(0xc4292c3700, 0x2, 0xffffffffffffffff, 0x0, 0x0, 0x0)
    /home/afr/go/src/github.com/yuin/gopher-lua/state.go:1662 +0xe3 fp=0xc425745fb0 sp=0xc425745f60
main.luaFunctionMap.func1.1(0xc42185d020, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
    /home/afr/go/src/github.com/xyproto/algernon/lua.go:605 +0x355 fp=0xc425746188 sp=0xc425745fb0
main.pongoPage.func1(0xc428ac2730, 0x2, 0x2, 0x0)
    /home/afr/go/src/github.com/xyproto/algernon/rendering.go:334 +0x134 fp=0xc425746200 sp=0xc425746188
runtime.call32(0xc420d19ad0, 0xc420f94ef0, 0xc42185d000, 0x1800000020)
    /usr/lib/go/src/runtime/asm_amd64.s:479 +0x4c fp=0xc425746230 sp=0xc425746200
reflect.Value.call(0xa67540, 0xc420f94ef0, 0x13, 0xb3714f, 0x4, 0xc421091d40, 0x1, 0x2, 0x0, 0xb1de60, ...)
    /usr/lib/go/src/reflect/value.go:434 +0x5c8 fp=0xc425746580 sp=0xc425746230
reflect.Value.Call(0xa67540, 0xc420f94ef0, 0x13, 0xc421091d40, 0x2, 0x2, 0x1, 0x2, 0x1)
    /usr/lib/go/src/reflect/value.go:302 +0xa4 fp=0xc4257465e8 sp=0xc425746580
github.com/flosch/pongo2.(*variableResolver).resolve(0xc42127e4c0, 0xc42159ef30, 0xc425746a48, 0x69858b, 0xc42185cf20)
    /home/afr/go/src/github.com/flosch/pongo2/variable.go:408 +0xfcd fp=0xc425746a08 sp=0xc4257465e8
github.com/flosch/pongo2.(*variableResolver).Evaluate(0xc42127e4c0, 0xc42159ef30, 0xc425746ad8, 0xc425746ae0)
    /home/afr/go/src/github.com/flosch/pongo2/variable.go:429 +0x4d fp=0xc425746a98 sp=0xc425746a08
github.com/flosch/pongo2.(*nodeFilteredVariable).Evaluate(0xc42159ea20, 0xc42159ef30, 0xc425c0cd20, 0xc)
    /home/afr/go/src/github.com/flosch/pongo2/variable.go:446 +0x42 fp=0xc425746ae8 sp=0xc425746a98
github.com/flosch/pongo2.(*nodeVariable).Execute(0xc42127e480, 0xc42159ef30, 0x105eaa0, 0xc420f300e0, 0x0)
    /home/afr/go/src/github.com/flosch/pongo2/variable.go:189 +0x42 fp=0xc425746b30 sp=0xc425746ae8
github.com/flosch/pongo2.(*nodeDocument).Execute(0xc42127e1e0, 0xc42159ef30, 0x105eaa0, 0xc420f300e0, 0xc42159ef00)
    /home/afr/go/src/github.com/flosch/pongo2/nodes.go:10 +0x72 fp=0xc425746b80 sp=0xc425746b30
github.com/flosch/pongo2.(*Template).execute(0xc421112090, 0xc42013d320, 0x105eaa0, 0xc420f300e0, 0x0, 0x173)
    /home/afr/go/src/github.com/flosch/pongo2/template.go:128 +0x313 fp=0xc425746cd0 sp=0xc425746b80
github.com/flosch/pongo2.(*Template).newBufferAndExecute(0xc421112090, 0xc42013d320, 0xc425746d78, 0x42e0f5, 0xc425746d70)
    /home/afr/go/src/github.com/flosch/pongo2/template.go:143 +0x108 fp=0xc425746d30 sp=0xc425746cd0
github.com/flosch/pongo2.(*Template).ExecuteWriter(0xc421112090, 0xc42013d320, 0x1059fe0, 0xc420f30000, 0xc420f8a4b0, 0xc42222ac20)
    /home/afr/go/src/github.com/flosch/pongo2/template.go:153 +0x39 fp=0xc425746d70 sp=0xc425746d30
main.pongoPage(0x1063c60, 0xc420066410, 0xc420f8a4b0, 0xc42222ac20, 0x18, 0xc42222acc0, 0x17, 0xc425c0cb40, 0x11e, 0x11e, ...)
    /home/afr/go/src/github.com/xyproto/algernon/rendering.go:372 +0x603 fp=0xc4257471f0 sp=0xc425746d70
main.filePage(0x1063c60, 0xc420066410, 0xc420f8a4b0, 0xc42222ac20, 0x18, 0x1069a60, 0xc420137bc0, 0xc420233500, 0xc420137c20)
    /home/afr/go/src/github.com/xyproto/algernon/handlers.go:214 +0x50aa fp=0xc425747a50 sp=0xc4257471f0
main.dirPage(0x1063c60, 0xc420066410, 0xc420f8a4b0, 0x7ffeca9e3701, 0x1, 0xc42222a220, 0x11, 0x1069a60, 0xc420137bc0, 0xc420233500, ...)
    /home/afr/go/src/github.com/xyproto/algernon/dirhandler.go:93 +0x2d1 fp=0xc425747b50 sp=0xc425747a50
main.registerHandlers.func1(0x1063c60, 0xc420066410, 0xc420f8a4b0)
    /home/afr/go/src/github.com/xyproto/algernon/handlers.go:422 +0x44c fp=0xc425747c68 sp=0xc425747b50
net/http.HandlerFunc.ServeHTTP(0xc420142230, 0x1063c60, 0xc420066410, 0xc420f8a4b0)
    /usr/lib/go/src/net/http/server.go:1726 +0x44 fp=0xc425747c90 sp=0xc425747c68
net/http.(*ServeMux).ServeHTTP(0xc4202093b0, 0x1063c60, 0xc420066410, 0xc420f8a4b0)
    /usr/lib/go/src/net/http/server.go:2022 +0x7f fp=0xc425747cd0 sp=0xc425747c90
net/http.serverHandler.ServeHTTP(0xc420190900, 0x1063c60, 0xc420066410, 0xc420f8a4b0)
    /usr/lib/go/src/net/http/server.go:2202 +0x7d fp=0xc425747d18 sp=0xc425747cd0
net/http.(*conn).serve(0xc423d66880, 0x10647e0, 0xc420d28080)
    /usr/lib/go/src/net/http/server.go:1579 +0x4b7 fp=0xc425747f78 sp=0xc425747d18
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc425747f80 sp=0xc425747f78
created by net/http.(*Server).Serve
    /usr/lib/go/src/net/http/server.go:2293 +0x44d
```

Steps to reproduce:

```
mkdir -p $GOPATH/github.com/xyproto
cd $GOPATH/github.com/xyproto
git clone https://github.com/xyproto/algernon
cd algernon
go get -d -t -v -u
go build && bench/stress_server.sh 2> output.txt
```

Then in a different terminal window:

```
cd $GOPATH/github.com/xyproto/algernon
bench/stress_client.sh
```

`output.txt` should contain the full backtrace and error messages. Do you think the problem is in `variable.go` in the pongo2 package?

I'm using Go 1.7.1 on 64-bit Arch Linux.

Any help resolving this is appreciated.

Best regards,
Alexander F Rødseth
##

**Comment by flosch** [comment]
You're altering a map which should be synchronized on your site.
