### ISSUE TITLE
bug: wordwrap panics when input has less words than needed to split

### ISSUE THREAD

**Issue by lrstanley** [flosch/pongo2#297]
Looks as though `wordwrap` doesn't support providing input that is less than the number of words which you pass into `wordwrap` to split. I assume this is a bug, as having to first check the word length, before passing into `wordwrap` doesn't make very much sense. Additionally, looks as though many default filters fallback if their input is less than required (e.g. truncating characters, words, etc).

Example:
```go
package main

import (
        "fmt"

        "github.com/flosch/pongo2/v5"
)

func main() {

        tpl, err := pongo2.FromString("Testing: {{ input|wordwrap:4 }}!") // split every 4
        if err != nil {
                panic(err)
        }

        out, err := tpl.Execute(pongo2.Context{"input": "one two"}) // only provide 2 words as input
        if err != nil {
                panic(err)
        }
        fmt.Println(out)
}
```

I've tested with both v5.0.0 and v4.0.2, both of these causing the following panic:
```console
$ go run main.go
panic: runtime error: slice bounds out of range [4:2]

goroutine 1 [running]:
github.com/flosch/pongo2/v5.filterWordwrap(0xc00007d260, 0xc00006c3e0)
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/filters_builtin.go:908 +0x265
github.com/flosch/pongo2/v5.(*filterCall).Execute(0xc00007d170, 0xc00007d290, 0xc00007d290)
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/filters.go:97 +0x72
github.com/flosch/pongo2/v5.(*nodeFilteredVariable).Evaluate(0xc00007d140, 0x40e594)
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/variable.go:464 +0x90
github.com/flosch/pongo2/v5.(*nodeVariable).Execute(0xc00000e318, 0xc00007d290, {0x62e188, 0xc00007d200})
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/variable.go:189 +0x3d
github.com/flosch/pongo2/v5.(*nodeDocument).Execute(0xc000160120, 0xc00016de30, {0x62e188, 0xc00007d200})
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/nodes.go:10 +0x8a
github.com/flosch/pongo2/v5.(*Template).execute(0xc00004e501, 0x413a59, {0x62e188, 0xc00007d200})
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/template.go:173 +0x45
github.com/flosch/pongo2/v5.(*Template).newBufferAndExecute(0xc000160120, 0x5ec827)
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/template.go:188 +0xcd
github.com/flosch/pongo2/v5.(*Template).Execute(0x5c3ac0, 0xc00016de30)
        /home/liam/go/pkg/mod/github.com/flosch/pongo2/v5@v5.0.0/template.go:231 +0x1d
main.main()
        /home/liam/tmp/pongo2-wordwrap-issue/main.go:15 +0x105
exit status 2
```

Using `go version go1.17.6 linux/amd64`.

**Comment by deroshkin** [comment]
The bug is actually more general, 6 words also triggered it.

Submitted pull request #308 to address it.

**Comment by lrstanley** [comment]
Closing as #308 was merged.
